int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _is_sqrt(int i, int num);
int is_prime_number(int n);
int _is_prime(int i, int num);
int is_palindrome(char *s);
int is_p(char *a, int i, int j);
int _strlen(char *str);
int wild(char *x, char *y, int zero, int hero);
int ascheck(char *s, char b, int k, int len);
int _strlen1(char *s);
int wildcmp(char *s1, char *s2);
